package com.pygman.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2014-10-30T14:28:31.250+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://service.ws.pygman.com/", name = "EbWSItemService")
@XmlSeeAlso({ObjectFactory.class})
public interface EbWSItemService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "publishItem", targetNamespace = "http://service.ws.pygman.com/", className = "com.pygman.stub.PublishItem")
    @WebMethod
    @ResponseWrapper(localName = "publishItemResponse", targetNamespace = "http://service.ws.pygman.com/", className = "com.pygman.stub.PublishItemResponse")
    public String publishItem(
            @WebParam(name = "arg0", targetNamespace = "")
            Long arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1
    );
}
